-- Paneru config — niri-like sliding strip. Modifier lanes:
-- Cmd+Option = columns, Ctrl+Option = dynamic workspace rows,
-- Cmd+Ctrl = displays, Cmd+Shift+? = shortcut cheat sheet.
-- Generated by paneru-wm-installer. Edit freely; live reload is on.
--
-- All Paneru keybindings live in BINDINGS below (command vs chord);
-- helpers/generate-shortcuts-json turns this table into the
-- mac-cheatsheet-viewer JSON.

local BINDINGS = {
  -- ─── Window focus (Cmd+Option+Arrows) ───
  ["window focus west"] = "cmd + alt - leftarrow",
  ["window focus east"] = "cmd + alt - rightarrow",
  ["window focus north"] = "cmd + alt - uparrow",
  ["window focus south"] = "cmd + alt - downarrow",

  -- ─── Move window (Cmd+Option+Shift+Arrows) ───
  ["window swap west"] = "cmd + alt + shift - leftarrow",
  ["window swap east"] = "cmd + alt + shift - rightarrow",
  ["window swap north"] = "cmd + alt + shift - uparrow",
  ["window swap south"] = "cmd + alt + shift - downarrow",

  -- ─── Column width (Cmd+Option+W) ───
  ["window resize"] = "cmd + alt - w",
  ["window shrink"] = "cmd + alt + shift - w",
  ["window fullwidth"] = "cmd + alt - m",

  -- ─── Workspaces (Ctrl+Option+↑/↓ = cycle dynamic rows; Shift = move & follow) ───
  ["window virtual north"] = "ctrl + alt - uparrow",
  ["window virtual south"] = "ctrl + alt - downarrow",
  ["window virtualmove north"] = "ctrl + alt + shift - uparrow",
  ["window virtualmove south"] = "ctrl + alt + shift - downarrow",
  ["window focus managed"] = "cmd + alt - tab",
  -- Workspace rows are created on demand (south past the last row spawns one)
  -- and reaped when empty; the 3-finger vertical swipe also cycles them.

  -- ─── Displays: navigation is handled by function binds below (the move
  -- resizes to full width only after the window has arrived; the helper
  -- needs to be on the target display first). Mouse warp stays here: ↑ = next. ───
  ["mouse nextdisplay"] = "cmd + ctrl - uparrow",

  -- ─── Window state ───
  ["window manage"] = "cmd + alt - v",           -- toggle tiled/floating
  ["window stack"] = "cmd + alt - o",            -- stack into the neighbour column
  ["window unstack"] = "cmd + alt + shift - o",  -- pull out of a stack into its own column
  ["window center"] = "cmd + alt - space",
  ["window snap"] = "cmd + alt + shift - space", -- snap an overflowing window into view
  ["window equalize"] = "cmd + alt + shift - e",
  ["window balance"] = "cmd + alt - b",          -- all columns match the focused width
  ["window copyrule"] = "cmd + alt + shift - c",

  -- ─── Misc ───
  ["restart"] = "cmd + alt + shift - r",
  ["quit"] = "cmd + alt + ctrl - q",
}

paneru.setup {
  -- ─── Global options ───
  options = {
    focus_follows_mouse = true,
    mouse_follows_focus = true,
    -- Horizontally stacked (side-by-side) monitors: arrange displays
    -- vertically in macOS, set this to -1 so edge crossings feel left/right.
    horizontal_mouse_warp = -1,
    horizontal_mouse_warp_offset = 0,
    preset_column_widths = { 0.3, 0.5, 1.0 },
    animation_speed = 12.0,
    auto_center = false,
    create_virtual_workspace_automatically = true,
    reap_empty_workspaces = true,
    window_resize_cycle = true,
  },

  -- ─── Screen padding (outer gaps; Paneru has no inner-gap option) ───
  padding = { top = 15, bottom = 15, left = 15, right = 15 },

  -- ─── Swipe & gestures ───
  swipe = {
    continuous = false,  -- page-flip: a swipe lands exactly on the next window
    sensitivity = 0.35,
    deceleration = 4.0,
    gesture = {
      fingers_count = 3,
      direction = "Natural",
      vertical = true,
    },
    scroll = { modifier = "cmd + alt" },
  },

  -- ─── Decorations ───
  -- Menu-bar workspace indicator is OFF by default: the status item hosts a
  -- live NSView, and AppKit's menu-bar replicant redraw loop starves the run
  -- loop that services Paneru's CGEventTap, so macOS disables the tap and
  -- keybindings silently stop working after leaving native fullscreen.
  -- Upstream fix: karinushka/paneru#390 (merged to main after v0.5.0). Keep
  -- workspace_menu_status = false until a release ships it; flipping it to
  -- true needs a `paneru restart`.
  decorations = {
    workspace_menu_status = false,
    workspace_popup_status = true,
    menu = {
      indicator = { style = "paged", format = "default", font_size = 13.0 },
    },
    inactive = { dim = { opacity = 0.0, opacity_night = 0.0 } },
    active = {
      border = {
        enabled = true,
        color = "#2b303cd6",
        opacity = 1.0,
        width = 4.0,
        radius = "auto",
      },
    },
  },

  bindings = BINDINGS,

  -- ─── Window rules ───
  windows = {
    calculator = { title = ".*", bundle_id = "com.apple.calculator", floating = true },
    preferences = { title = "Preferences", floating = true },
    -- Inner gaps: Paneru has no global inner-gap option, so this applies
    -- per-window padding to every tiled window.
    default = { title = ".*", horizontal_padding = 8, vertical_padding = 8 },
  },

  -- ─── Session restore (startup-only) ───
  restore = {
    enabled = true,
    startup_grace_ms = 2000,
    missing_windows = "ignore",
  },
}

-- ─── Display navigation ───
-- Cmd+Ctrl+←/→ shift focus to another display without moving the window,
-- using geometric display order (sorted by macOS arrangement position).
-- Cmd+Ctrl+Shift+←/→ moves the focused window to the previous/next display
-- and follows it.
--
-- Paneru itself can only move a window to a single fixed display
-- (`other().next()` in its ECS), which on 3+ display setups cannot reach
-- every monitor. With exactly two displays a single `nextdisplay` hop
-- suffices (previous and next are the same display). With three or more the
-- window is floated, teleported (AppleScript/Accessibility, via the external
-- ~/.config/mac-scrolling-wm/helpers/move-display) onto the target display's
-- frame, and brought into focus there so Paneru's active-display marker
-- rotates.
--
-- Either way, resizing to full width must wait until Paneru's active-display
-- marker has actually rotated to the destination (it only updates on a
-- `DisplayChanged` event, which neither `nextdisplay` nor the teleport fire
-- themselves — resizing any earlier can apply against the wrong display, or
-- race Paneru's own internal post-move resize and visibly double up). Both
-- paths settle through the same `settle_after_move` below, which polls
-- Paneru's state in-process (`paneru.query_active`/`query_json`, no
-- subprocess spawn) instead of sleeping a guessed amount.
--
-- While a move is mid-flight (3+ displays only — the 2-display path never
-- floats) the focused window is *floating*. Paneru's Lua `display_of`
-- resolves a window's display by strip membership, which lags the physical
-- teleport, so both focus and move skip while the focused window is
-- floating — that is what stops rapid re-presses from computing targets off
-- a stale "current" display and bouncing windows back to the wrong monitor.

-- Helpers installed alongside move-display (layout, see helpers/):
--   display-geometry — real CG frames of every online display, empties included
--   warp-pointer    — drop the cursor on an absolute point (focus an empty display)
local MOVE_HELPER = os.getenv("HOME") .. "/.config/mac-scrolling-wm/helpers/move-display"
local GEOM_HELPER = os.getenv("HOME") .. "/.config/mac-scrolling-wm/helpers/display-geometry"
local WARP_HELPER = os.getenv("HOME") .. "/.config/mac-scrolling-wm/helpers/warp-pointer"

-- ─── Display geometry cache ───────────────────────────────────────────────
-- Paneru's Lua `display_of` resolves a display by *membership*, so a monitor
-- with no windows is invisible to it and navigation cannot reach it. The real
-- display list (all online displays, cached here and refreshed on display
-- events / on a detected geometry mismatch) is what ordering and targeting use.
local DISPLAYS = {}      -- display_id -> { id, x, y, width, height }
local ORDERED_IDS = {}   -- display ids in geometric order (y, then x, ascending)
local GEOM_STALE = true

local function sort_ordered_ids()
  table.sort(ORDERED_IDS, function(a, b)
    if DISPLAYS[a].y ~= DISPLAYS[b].y then return DISPLAYS[a].y < DISPLAYS[b].y end
    return DISPLAYS[a].x < DISPLAYS[b].x
  end)
end

local function refresh_geometry()
  local ok, res = pcall(paneru.exec, GEOM_HELPER, {})
  if not ok or not res or res.code ~= 0 then return false end
  local t, ids = {}, {}
  for line in (res.stdout or ""):gmatch("[^\r\n]+") do
    local id, x, y, w, h = line:match("(%d+)%s+(%d+)%s+(%d+)%s+(%d+)%s+(%d+)")
    if id then
      id, x, y, w, h = tonumber(id), tonumber(x), tonumber(y), tonumber(w), tonumber(h)
      t[id] = { id = id, x = x, y = y, width = w, height = h }
      ids[#ids + 1] = id
    end
  end
  if #ids == 0 then return false end
  DISPLAYS, ORDERED_IDS, GEOM_STALE = t, ids, false
  sort_ordered_ids()
  return true
end

-- Re-read geometry when the cached set went stale, or when any window sits on
-- a display we know nothing about (a display appeared outside an event).
local function ensure_geometry(ws)
  if GEOM_STALE then
    if refresh_geometry() then return end
  else
    for _, w in ipairs(ws:windows()) do
      local d = ws:display_of(w.id)
      if d and not DISPLAYS[d.id] then
        GEOM_STALE = true
        refresh_geometry()
        return
      end
    end
  end
end

-- Geometric display ordering (all physical displays, empty ones included).
local function ordered_displays(ws)
  ensure_geometry(ws)
  if #ORDERED_IDS >= 2 then return ORDERED_IDS end
  -- geometry helper unavailable: fall back to window-derived ordering
  local displays = {}
  for _, w in ipairs(ws:windows()) do
    local d = ws:display_of(w.id)
    if d and not displays[d.id] then
      displays[d.id] = { id = d.id, x = d.x, y = d.y }
    end
  end
  local ids = {}
  for id in pairs(displays) do ids[#ids + 1] = id end
  table.sort(ids, function(a, b)
    if displays[a].y ~= displays[b].y then return displays[a].y < displays[b].y end
    return displays[a].x < displays[b].x
  end)
  return ids
end

local function focused_on_display(ws, display_id)
  for _, w in ipairs(ws:windows()) do
    local d = ws:display_of(w.id)
    if d and d.id == display_id and w.focused then return w.id end
  end
  for _, w in ipairs(ws:windows()) do
    local d = ws:display_of(w.id)
    if d and d.id == display_id then return w.id end
  end
end

local function focus_display(ws, target)
  local focused = ws:focused()
  if not focused then return end
  local win = ws:window(focused)
  if win and win.floating then return end  -- a window move is in flight; don't jump
  local cur = ws:display_of(focused)
  local ids = ordered_displays(ws)
  if not cur or #ids < 2 then return end
  local idx
  for i, id in ipairs(ids) do if id == cur.id then idx = i break end end
  if not idx then return end
  local n = #ids
  local step = (target == "previous") and (n - 1) or 1
  local target_id = ids[((idx - 1 + step) % n) + 1]
  local win = focused_on_display(ws, target_id)
  if win then return ws:focus(win) end
  -- Target display has no windows: drop the pointer on its center so the OS
  -- treats it as the active display (the same idea as `mouse nextdisplay`).
  local t = DISPLAYS[target_id]
  if t then
    paneru.exec(WARP_HELPER, { string.format("%d %d", math.floor(t.x + t.width / 2), math.floor(t.y + t.height / 2)) })
  end
end

local function display_frame(ws, display_id)
  ensure_geometry(ws)
  local t = DISPLAYS[display_id]
  if t then return t end
  for _, w in ipairs(ws:windows()) do
    local d = ws:display_of(w.id)
    if d and d.id == display_id then return d end
  end
end

-- ─── Settle-after-move ─────────────────────────────────────────────────────
-- Shared by both display-move paths below: wait for Paneru's active-display
-- marker to actually reach the target (in-process query, no subprocess), then
-- re-manage/verify adoption, and resize only once landed. This is the one and
-- only place either path resizes.
local SETTLE_POLL_TICKS = 60   -- in-process query round-trips; cheap, so generous
local SETTLE_ATTEMPTS = 3

local function wait_active_display(target_id)
  for _ = 1, SETTLE_POLL_TICKS do
    local ok, active = pcall(paneru.query_active)
    if ok and active and active.display_id == target_id then return true end
  end
  return false
end

-- A handful of query round-trips as a cheap in-process "let a tick or two of
-- Paneru's dispatch loop pass" — used after a mutating `paneru.run` so the
-- verify check below doesn't read state from before the command applied.
local function settle_ticks(n)
  for _ = 1, n do pcall(paneru.query_active) end
end

-- The moved window's own {window_id, floating, display_id} from a fresh
-- state query, or nil if it can't be found (e.g. between strips).
local function window_state(window_id)
  local ok, state = pcall(paneru.query_json, "state")
  if not ok or not state then return nil end
  for _, row in ipairs(state.virtual_workspaces or {}) do
    for _, w in ipairs(row.windows or {}) do
      if w.window_id == window_id then return w end
    end
  end
end

local function adopted(target_id, moved_window_id)
  local ok, active = pcall(paneru.query_active)
  if not ok or not active or active.display_id ~= target_id then return false end
  local w = window_state(moved_window_id)
  return w ~= nil and w.floating == false and w.display_id == target_id
end

local function settle_after_move(ws, target_id, moved_window_id)
  for _attempt = 1, SETTLE_ATTEMPTS do
    if wait_active_display(target_id) then
      -- focus_follows_mouse can steal focus mid-hop; steer it back so the
      -- re-manage below (if any) tiles the window that actually moved.
      local ok, active = pcall(paneru.query_active)
      if ok and active and active.focused_window_id ~= moved_window_id then
        ws:focus(moved_window_id)
      end
      local w = window_state(moved_window_id)
      if w and w.floating then
        paneru.run("window manage")  -- re-tile onto the now-active strip
        settle_ticks(5)
      end
      if adopted(target_id, moved_window_id) then
        paneru.run("window fullwidth")
        return true
      end
    end
    -- Not adopted: float it again so the next attempt's manage re-tiles it
    -- onto the active strip (mirrors the previous bash helper's retry).
    local w = window_state(moved_window_id)
    if w and w.floating == false then
      paneru.run("window manage")
      settle_ticks(5)
    end
  end
  paneru.flash("move-display: failed to adopt target display", 3.0)
  return false
end

local function move_to_display(ws, target)
  local focused = ws:focused()
  if not focused then return end
  local win = ws:window(focused)
  if win and win.floating then return end  -- a move is already in flight (helper busy); ignore re-presses
  local cur = ws:display_of(focused)
  local ids = ordered_displays(ws)
  if not cur or #ids < 2 then return end
  local n = #ids
  if n == 2 then
    local other_id
    for _, id in ipairs(ids) do if id ~= cur.id then other_id = id end end
    paneru.run("window nextdisplay")
    settle_after_move(ws, other_id, focused)
    return
  end
  local idx
  for i, id in ipairs(ids) do if id == cur.id then idx = i break end end
  if not idx then return end
  local step = (target == "previous") and (n - 1) or 1
  local target_id = ids[((idx - 1 + step) % n) + 1]
  if target_id == cur.id then return end
  local t = display_frame(ws, target_id)
  if not t then
    paneru.flash("move-display: no geometry for target display", 3.0)
    return
  end
  local ok, active = pcall(paneru.query_active)
  local app_name = ok and active and active.focused_app_name or ""
  paneru.run("window manage")  -- float, so it can be teleported off its strip
  settle_ticks(5)
  local exec_ok, res = pcall(paneru.exec, MOVE_HELPER, { app_name, string.format("%d", t.x), string.format("%d", t.y) })
  if not exec_ok or not res or res.code ~= 0 then
    paneru.flash("move-display: teleport failed", 3.0)
    local w = window_state(focused)
    if w and w.floating then paneru.run("window manage") end  -- leave it tiled somewhere clean
    return
  end
  settle_after_move(ws, t.id, focused)
end

-- ─── Keybindings ───
-- Focus only: window stays put, no maximize.
paneru.bind("cmd + ctrl - leftarrow", function(ws) return focus_display(ws, "previous") end)
paneru.bind("cmd + ctrl - rightarrow", function(ws) return focus_display(ws, "next") end)
-- Move window + follow; full width is applied at the destination, after arrival.
paneru.bind("cmd + ctrl + shift - leftarrow", function(ws) move_to_display(ws, "previous") end)
paneru.bind("cmd + ctrl + shift - rightarrow", function(ws) move_to_display(ws, "next") end)

-- Any display event invalidates the geometry cache (re-read on next use).
for _, evt in ipairs({ "display_added", "display_removed", "display_moved",
                        "display_resized", "display_configured", "display_changed" }) do
  paneru.on(evt, function() GEOM_STALE = true end)
end

-- Cmd+Shift+? (slash key) opens the shortcut cheat sheet: regenerate the JSON
-- from BINDINGS above, then show it in mac-cheatsheet-viewer.
paneru.bind("cmd + shift - slash", function()
  paneru.exec(os.getenv("HOME") .. "/.config/mac-scrolling-wm/helpers/display-shortcuts")
end)