-- Paneru config — niri-like sliding strip. Modifier lanes:
-- Cmd+Option = columns, Ctrl+Option = dynamic workspace rows,
-- Cmd+Ctrl = displays, Cmd+Shift+? = shortcut cheat sheet.
-- Generated by paneru-wm-installer. Edit freely; live reload is on.
--
-- All Paneru keybindings live in BINDINGS below (command vs chord);
-- helpers/generate-shortcuts-json turns this table into the
-- mac-cheatsheet-viewer JSON.

local BINDINGS = {
  -- ─── Window focus (Cmd+Option+Arrows) ───
  ["window focus west"] = "cmd + alt - leftarrow",
  ["window focus east"] = "cmd + alt - rightarrow",
  ["window focus north"] = "cmd + alt - uparrow",
  ["window focus south"] = "cmd + alt - downarrow",

  -- ─── Move window (Cmd+Option+Shift+Arrows) ───
  ["window swap west"] = "cmd + alt + shift - leftarrow",
  ["window swap east"] = "cmd + alt + shift - rightarrow",
  ["window swap north"] = "cmd + alt + shift - uparrow",
  ["window swap south"] = "cmd + alt + shift - downarrow",

  -- ─── Column width (Cmd+Option+W) ───
  ["window resize"] = "cmd + alt - w",
  ["window shrink"] = "cmd + alt + shift - w",
  ["window fullwidth"] = "cmd + alt - m",

  -- ─── Workspaces (Ctrl+Option+↑/↓ = cycle dynamic rows; Shift = move & follow) ───
  ["window virtual north"] = "ctrl + alt - uparrow",
  ["window virtual south"] = "ctrl + alt - downarrow",
  ["window virtualmove north"] = "ctrl + alt + shift - uparrow",
  ["window virtualmove south"] = "ctrl + alt + shift - downarrow",
  ["window focus managed"] = "cmd + alt - tab",
  -- Workspace rows are created on demand (south past the last row spawns one)
  -- and reaped when empty; the 3-finger vertical swipe also cycles them.

  -- ─── Displays: navigation is handled by function binds below (the move
  -- keeps the window's exact size/disposition — no resize, no float/tile
  -- change). Mouse warp stays here: ↑ = next. ───
  ["mouse nextdisplay"] = "cmd + ctrl - uparrow",

  -- ─── Window state ───
  ["window manage"] = "cmd + alt - v",           -- toggle tiled/floating
  ["window stack"] = "cmd + alt - o",            -- stack into the neighbour column
  ["window unstack"] = "cmd + alt + shift - o",  -- pull out of a stack into its own column
  ["window center"] = "cmd + alt - space",
  ["window snap"] = "cmd + alt + shift - space", -- snap an overflowing window into view
  ["window equalize"] = "cmd + alt + shift - e",
  ["window balance"] = "cmd + alt - b",          -- all columns match the focused width
  ["window copyrule"] = "cmd + alt + shift - c",

  -- ─── Misc ───
  ["restart"] = "cmd + alt + shift - r",
  ["quit"] = "cmd + alt + ctrl - q",
}

paneru.setup {
  -- ─── Global options ───
  options = {
    focus_follows_mouse = true,
    -- mouse_follows_focus = true,
    -- Horizontally stacked (side-by-side) monitors: arrange displays
    -- vertically in macOS, set this to -1 so edge crossings feel left/right.
    horizontal_mouse_warp = -1,
    horizontal_mouse_warp_offset = 0,
    preset_column_widths = { 0.3, 0.5, 1.0 },
    animation_speed = 12.0,
    auto_center = true,
    create_virtual_workspace_automatically = true,
    reap_empty_workspaces = true,
    window_resize_cycle = true,
  },

  -- ─── Screen padding (outer gaps; Paneru has no inner-gap option) ───
  padding = { top = 15, bottom = 15, left = 15, right = 15 },

  -- ─── Swipe & gestures ───
  swipe = {
    continuous = true,  -- page-flip: a swipe lands exactly on the next window
    sensitivity = 0.35,
    deceleration = 4.0,
    gesture = {
      fingers_count = 3,
      direction = "Natural",
      vertical = true,
    },
    scroll = { modifier = "cmd + alt" },
  },

  -- ─── Decorations ───
  -- Menu-bar workspace indicator is OFF by default: the status item hosts a
  -- live NSView, and AppKit's menu-bar replicant redraw loop starves the run
  -- loop that services Paneru's CGEventTap, so macOS disables the tap and
  -- keybindings silently stop working after leaving native fullscreen.
  -- Upstream fix: karinushka/paneru#390 (merged to main after v0.5.0). Keep
  -- workspace_menu_status = false until a release ships it; flipping it to
  -- true needs a `paneru restart`.
  decorations = {
    workspace_menu_status = false,
    workspace_popup_status = true,
    menu = {
      indicator = { style = "paged", format = "default", font_size = 13.0 },
    },
    inactive = { dim = { opacity = 0.0, opacity_night = 0.0 } },
    active = {
      border = {
        enabled = true,
        color = "#2b303c",
        opacity = 0.84,
        width = 4.0,
        radius = "auto",
      },
    },
  },

  bindings = BINDINGS,

  -- ─── Window rules ───
  windows = {
    calculator = { title = ".*", bundle_id = "com.apple.calculator", floating = true },
    preferences = { title = "Preferences", floating = true },
    -- Inner gaps: Paneru has no global inner-gap option, so this applies
    -- per-window padding to every tiled window.
    default = { title = ".*", horizontal_padding = 8, vertical_padding = 8 },
  },

  -- ─── Session restore (startup-only) ───
  restore = {
    enabled = true,
    startup_grace_ms = 2000,
    missing_windows = "ignore",
  },
}

-- ─── Module search path ───
-- Paneru's Lua runtime enables `require` (StdLib::ALL) but does not add the
-- config directory to `package.path` itself, so this config does it: modules
-- in lib/ (log.lua, query.lua, displays.lua) become requireable as
-- "lib.<name>" from this file. Only this file is filesystem-watched for hot
-- reload — editing a lib/*.lua file alone will not trigger it; touch this
-- file too (or run `paneru restart`) to pick up a library-only edit.
local CONFIG_DIR = (os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")) .. "/paneru/"
package.path = CONFIG_DIR .. "?.lua;" .. CONFIG_DIR .. "?/init.lua;" .. package.path

-- ─── Display navigation (config/paneru/lib/displays.lua) ───
-- Cmd+Ctrl+←/→ shift focus to another display without moving the window.
-- Cmd+Ctrl+Shift+←/→ moves the focused window to the previous/next display
-- and follows it. See lib/displays.lua for the full design notes (Paneru's
-- native single-hop "next display" limitation, empty-display reachability,
-- 3+ display teleport via helpers/move-display, and the settle/retry logic).
local displays = require("lib.displays")

-- ─── Keybindings ───
-- Focus only: window stays put, nothing resized.
paneru.bind("cmd + ctrl - leftarrow", function(ws) return displays.focus(ws, "previous") end)
paneru.bind("cmd + ctrl - rightarrow", function(ws) return displays.focus(ws, "next") end)
-- Move window + follow; size and tiled/floating disposition are preserved exactly.
paneru.bind("cmd + ctrl + shift - leftarrow", function(ws) displays.move(ws, "previous") end)
paneru.bind("cmd + ctrl + shift - rightarrow", function(ws) displays.move(ws, "next") end)

-- Workspace rows (window virtual north/south, window virtualmove north/south)
-- are plain BINDINGS-table entries above: Paneru already restores the right
-- scroll position after a virtual-workspace switch on its own (a one-tick-
-- delayed EnsureVisibleMarker correction, see ecs/layout.rs upstream) — an
-- extra `window snap` here used to race that native correction and caused a
-- visible jitter on arrival, without fixing anything the native correction
-- doesn't already handle.

-- Cmd+Shift+? (slash key) opens the shortcut cheat sheet: regenerate the JSON
-- from BINDINGS above, then show it in mac-cheatsheet-viewer.
paneru.bind("cmd + shift - slash", function()
  paneru.exec(os.getenv("HOME") .. "/.config/mac-scrolling-wm/helpers/display-shortcuts")
end)